apiVersion: apps/v1
kind: Deployment
metadata:
  name: shbr-echo-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shbr-echo
  template:
    metadata:
      labels:
        app: shbr-echo
        version: "2"
    spec:
      containers:
        - image: cr.yandex/crpamim8dasm0u97qtpf/shbr-01-package-docker:latest
          name: shbr-echo
          env:
            - name: PREFIX
              value: "World, "
      restartPolicy: Always
